### ISSUE TITLE
Create header component

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#1]
Create a `Header` jsx component:

- Has a list of navigation entries
- For now the elements can be hard-coded
- The navigation elements don't have to work/navigate anywhere (there will be a separate task for wiring-up the navigation)
- Create basic styles
  - horizontal layout
  - padding and margin between elements
  - drop shadow
 
Add the `Header` to the `App` Component

- Add component to .jsx
- Add styling in `App` to add a sticky top position of the `Header`

Designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=0287358f-ba0f-80b3-8001-af163e079ce4&section=interactions&index=0

**Comment by fromITzerotoIThero** [comment]
Hello Witia, I've no idea what's going on!

**Comment by piotrwicijowski** [comment]
Hello fIztIh, I'll fill in the description later

**Comment by fromITzerotoIThero** [comment]
Hey W., when creating all those components, you want me to stick to the design you've created (I mean the color, fonts, etc,)?

**Comment by piotrwicijowski** [comment]
Hi G., the designs should be treated as guidelines without having to be exactly pixel perfect in every details. That being said, at least for now, when it comes to those specifics:

- colors - right now just use the generic grey that is in the welcome screen for the accents, because for future work related to per-domain color theming we have an open task #10 
- font - you don't need to use that specific font, the built in sans serif font should work just fine. In the future we will think of adding a specific font as well
- font sizes, margins, paddings - this can be used explicitly as in the designs. In most cases I tried to use multiples of 4px, so if something looks a bit off, then you can make small adjustments as you see fit, e.g. if you see 13px, it will most likely be better as 12px, or if the height is 41px, I probably meant to use 40px

**Comment by fromITzerotoIThero** [comment]
Ayay Sir!

**Comment by fromITzerotoIThero** [comment]
W., I see we have different default indentation settings, I go with 4, you go with 2, want me to switch to 2?

**Comment by fromITzerotoIThero** [comment]
I decided to change rules for indent in eslintrc.json to 4 and the error was fixed :)

**Comment by piotrwicijowski** [comment]
If you install an [Editor](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) addon in VSCode, then it should automatically fix your indentation based on eslintrc. For me both 2 and 4 spaces work fine, as long as it is consistent in the whole codebase

**Comment by piotrwicijowski** [comment]
Side question - do we need all of those `index.js` files that just import and export, as well as an empty Navbar component?

**Comment by fromITzerotoIThero** [comment]
Frankly, I'm not sure, it did feel a little weird when creating! XD 
But the guy in the tutorial said that it does some good job when it comes down to referencing sources and with my tendency to overthink things I decided just to drop it this time and do what the guy tells me to ;P

With the navbar - I created it before I realised that instead of thinking how the project and its components might evolve over time, I should stick to the task as much as possible. And then oops... with my first commit on my very own, I've added everthing... 
Confusing, isn't it? I've pushed (that's the right word?) the commit and I was like "aaah, the message not really corresponding to what i did, the task not finished" and felt like it's not best practice for sure!

**Comment by piotrwicijowski** [comment]
Those additional index.js files are not really needed. I'm actually interested in which tutorial has this information - if you could send over the link, I'll have a look at it to understand what "the guy's" intention was ;)

Also, if you are having issues with styling, like sticky header, then feel free to commit the changes and let me know, maybe I can help you sort it out.

**Comment by fromITzerotoIThero** [comment]
There you go my Dear, 

https://youtu.be/YwgdzwNYico?t=119

In the first video he presents himself as a mainly backend dev without of any claims of being a frontend/react whiz, I do take what he says with a pinch of salt ;)

Aaaah, I bet you could sort it all out in a second, but I wouldn't want to take too much of your time, especially that I know it's scarce! And the answers are  all there somewhere on the web, I just need to do some digging, you'd be surprised to find how much digging I have to each day! XP 
That's probably the reason why it takes me so long to complete the tasks... I feel this is the right way, I mean trying to do as much as I can on my own, being self-reliant.  But then comes the issue of efficiency... :o! I think we could talk a bit about it tomorrow ;)

**Comment by fromITzerotoIThero** [comment]
See... pushing commits the way they work is even an issue for me XP for now ;)

**Comment by piotrwicijowski** [comment]
It all looks great so far, there are just a couple of small requirements remaining:
- make the header sticky
- use `*.module.css` approach in your Header component

**Comment by fromITzerotoIThero** [comment]
Um, that's a good question! I'm not sure what the consequences of closing a task here are, but since the header looks and works decently (except for this hard-coding), for the time being, I guess we can? 
Want me to click this button "Close with comment"?

**Comment by piotrwicijowski** [comment]
Sure, go ahead and try it :)
For now let's stick with a simple workflow, in which you can close task when you feel that is done. We'll work on more complex flow sometime in the future.

**Comment by fromITzerotoIThero** [comment]
OK! :)

**Comment by fromITzerotoIThero** [comment]
W., in Header.module.css I've added some questions in form of a comment to be asked in our next meeting, writing it down like this makes it easier for me to remember things, does my Dear Mentor green-light it or should I find some other way to do it?

**Comment by piotrwicijowski** [comment]
At least for now we can go with such an approach, but long-term (e.g. once we start using Pull Requests) it will be better to not treat the source code as communication medium
