### ISSUE TITLE
Robust color theming of various elements based on the "domain color"

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#10]
Make sure that the components for displaying domain-specific information (like BasicCard, or Accordion) can be parametrized in a way that allows the consumer of this component to set the theming color (in most cases a narrow rectangle on the left, or background color of the DomainHeader), so that each theme-able component does not have to re-implement each color of the domain in their styles
Possible solution - use css custom properties, also know as css variables https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties . This way the parent component could set the `--theme-color` variable, and the components can just be styled like `background-color: var(--theme-color)`

**Comment by fromITzerotoIThero** [comment]
W., 
I did some digging and came up with an idea how to apply custom theme colors - it does work fine on the consumer of `BasicCard` components, but for some reason it doesn't on the `DomainHeader` though done in the same manner. 

Funny thing (happened twice) - the browser did actually render the right color for `DomainDetails` for like 2 seconds after saving changes, but then it'd throw an error that `domain.name is undefined` which seems weird to me. 

Don't feel urged to answer, I have a lot of other stuff to finish anyway, enjoy your vacation ;)

**Comment by fromITzerotoIThero** [comment]
Whoops, I've deleted changes that broke `DomainDetails`, I'll add them back in a minute :)

**Comment by fromITzerotoIThero** [comment]
And I'veapplied theme colors to `AccordionElements` with success :) 
I'll try to tweak and dry up the code later on, there's probably a cleaner way to do the task.

**Comment by piotrwicijowski** [comment]
I can see you have made the `BasicCard` component be aware of four different themes. It would be best if generic components would just use the `--theme-color` and parent components/pages would set that value

**Comment by fromITzerotoIThero** [comment]
I did it the way I understand you suggested, but that doesn't work - is that the issue of specificity?

**Comment by piotrwicijowski** [comment]
I can see you configure the classes in `DomainsOverview.module.css` but you don't use those classes in `DomainsOverview.jsx`, that's why it does not work

**Comment by fromITzerotoIThero** [comment]
So this `theme_color` props doesn't do the job? 
 
`<div>
            {domains.map(domain =>
                <BasicCard theme_color={domain.name.toLowerCase().replace(' ', '-')} title={domain.name} description=                            {domain.short_description} buttonText="Learn more" buttonLink={`/domaindetails/${domain.id}`} key={domain.id}/>
            )}
        </div>`

**Comment by piotrwicijowski** [comment]
Is it using the class that you have defined in the `...module.css`? It doesn't seem like it, so no.
Instead maybe wrap each BasicCard in a `<div>` and set a `className` on each, based on similar logic of `domain.name.somethingsomething`

And if you are interested in why it is not working - remember that we are using css modules, so the names of the classes are unique and scoped for a component, and other components cant use the classes we defined elsewhere. So if in component A you defined a class `.executing`, and in component B you tried to use a class with such a name, it won't work. Even if the components are parent/child

**Comment by fromITzerotoIThero** [comment]
I've changed the code based on your suggestions (to the best of my understanding) but I still don't know why `DomainDetails` page doesn't know what `{domain.name}` is, aren't we fetching that data? 

Though it may not be of much help anyway...

**Comment by piotrwicijowski** [comment]
So, at the very beginning of the rendering pass, even before the data is retrieved from the back-end, React still wants to render something. And since in the JSX it sees `domain.name.somethingsomething` it tries to access that. That's true, we are fetching that, but by default React does not block the rendering during fetching - it shows whatever it has, and once the data arrives, it re-renders with the new data.

There are several options to make your code more resistant against situations where we don't have all the data yet. The simplest would be to set the initial state to `null` (in the `useState`) and then just conditionally wrap everything in a your return with { domain != null ? <RenderEverything> : <div>Loading</div>}. There are other options, but they are more involved.

**Comment by fromITzerotoIThero** [comment]
OK, well, that makes sense! I have a lot of things to learn! Thx for your explanation! :)
