### ISSUE TITLE
Dismiss welcome card

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#11]
As a user, if I open the web page for the first time, I want to see the welcome card to be displayed on the landing page. However, if I dismiss the card by clicking on the X button in the top right corner, I want the card to be closed and I want the browser to remember this choice in local storage.

Technical implementation details:
- Add a close button to the card component
- The close button calls an action/function that is outside of the card itself, so that we can have custom logic for handling that in different scenarios where the card would be used
- The close button should be optional. This means there should be a property, which dictates that this button should or should not be displayed. By default the close button should not be displayed
- For persisting the storage of the "has welcome card been closed" **flag** use localStorage browser API (you can either use the methods directly, or via some npm package)
- If the flag does not exist, the welcome screen should display the welcome card
- Once the user clicks on the close button on the welcome screen card, hide the welcome card and save the flag to the storage
- If the flag is set when opening the page, make sure not to display the welcome card

Link to the designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=aa6c056f-666a-8012-8001-dfd5bc1f9f51&section=interactions&index=0

**Comment by piotrwicijowski** [comment]
1. I'd say that the localStorage code for that specific behavior can live in `WelcomeScreen` component, it doesn't have to go all the way up to App (the app has no interest in knowing it)
2. If in the BasicCard's usage  in the `WelcomeScreen` component you do `onClose={handleWelcomeScreenClose}` then it should work just fine
3. If you want to see the localStorage, you can go to the devtools, and in firefox under storage, and in chrome under application you can get the access to the entries in the storage. There you can delete/clear specific entries of the localStorage just for debuging purposes

Anyway, you are very close

**Comment by fromITzerotoIThero** [comment]
W., I've changed the code dismissing the `WelcomeScreen` a bit, in a way that's a bit more straightforward for my head, it seems to work, but I have a couple of questions:

1. The `shouldShow()` function is written outside of the body of the `WelcomeScreen` function but I can't really remember what we said about it - whether it's a better option and if so, why. Should I leave it that way?

2. In the previous version of `shouldShow()` function we were checking this `null` condition:
`if(hasClosedWelcomeScreen == null) { result = true}`
and but it didn't work when I've changed the new version with `null` (though seems to work with "false") and I'm not sure why. Is the new version working just fine or am I missing something?

**Comment by fromITzerotoIThero** [comment]
Oh, and one more thing! :)

In the `WelcomeScreen` component I should use the `useCallback` hook, because the `handleWelcomeScreenClose()` is a 'big thing' for the CPU when React does all that 'preventive rendering` and that would make the function run only once - did I get it right?

**Comment by piotrwicijowski** [comment]
1. The `shouldShow()` function can be outside, because it does not use any variables/constants that are in the scope of the component. If it used something that e.g. is created via the `useState` (like your callback does) then it would **have to** live inside the component. If it doesn't have to live inside component, then it is better to leave it outside.
2. It works now, because even though you are not explicitly checking for the ` == null` condition, in case the value would be null, then it will use the default defined in the `shouldShow` function (line 41 - you define the default as `true`). And since that is the expected behavior for `null`, it works.

About the `useCallback` - you are almost right - the 'big thing' for the CPU is not running the `handle...` function (since it will only be run when we click on the button). Instead the 'big thing' is **creating** the function definition every time React does this 'preventive rendering'. So yes, definitely apply the `useCallback`, and that is an advice in every situation where we have a function definition inside the component's scope (also that is one of the reasons why we want to kee the `shouldShow()` outside - so that we don't have to bother with the `useCallback` for it)

**Comment by fromITzerotoIThero** [comment]
W., a request for a review - I used `useCallback` for `handleWelcomeScreenClose` function:

1. but I'm not sure why the `visibleWelcomeScreen` inside the dependency array is underlined...?  

2. also I'm not sure how to evaluate if it works - I mean at first glance the `WelcomeScreen` works the way it should but since there is no data within the console's `cache storage` then I guess no caching took place?

**Comment by piotrwicijowski** [comment]
1. Weird, it does not get underlined for me. What does it say when you hover over the underline? We can have a talk about it next time we meet, but I have a strong suspicion what it may be caused by.
2. The reason why there is nothing in `cache storage` is because we are not using `cache storage`. We are using `local storage`, and that's a different thing. You were just looking in the wrong place.

**Comment by fromITzerotoIThero** [comment]
1. That's a funny thing - the moment I opened up VS code it was fine, but now it's underlined again... we'll see about that next time then :)
 
2. Stupid me, I thought for some weird reason that when they write about 'caching' it has to do only with the browser's cache, I don't know all these mechanisms yet XP I still can't tell if the function was 'memoised' or whatever they call it XP It works fine?
