### ISSUE TITLE
Simple pagination of the product list

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#14]
As a user, when I open the product list page, I don't want all products to load, but instead I want the results to be paginated.

Technical implementation details:
- When fetching data, get only 10 items each time
- Add next/previous page buttons at the bottom of the page
- Store the page number in the query string parameter
- When loading a page with the query string already in place, make sure to load that page, and not the first page
- Back/forward navigation in the browser should work as expected

Design url: https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=aa6c056f-666a-8012-8001-dfd5bc1f9f51&section=interactions&index=1

NOT in the scope of this task:
- page number display
- number of pages
- go to page input
- pages that are close-by, e.g. 1... 5 6 **7** 8 9 ... 20

**Comment by fromITzerotoIThero** [comment]
W., 

I wanted to finalize this task, but for that I need a clue from you :)

So, it seems to me that routing/URLS/retrieving data from URLs is still somewhat a vague idea for me - I mean, I feel like I know quite a lot about each separately but not enough about how they cooperate. I guess it'll come to me, say, "organically", soon :)

But before that happens, I wanted to ask you - isn't the fact that `ProductList` is being rendered by `WelcomeScreen` component kind of complicating things when it comes down to routing and those URL params? 

I'm trying to visualize how the URLs should look like when I'm on homepage and `page 1` of `ProductList` shows:
`https://ibos.netlify.app/`?
And when I'm on subsequetn pages of of `ProductList` (still rendered by WelcomeScreen) should it be: 
`https://ibos.netlify.app/?page=2`, 
`https://ibos.netlify.app/?page=3`, 
`https://ibos.netlify.app/?page=4`...?

If so, wouldn't it be clearer (more readable?) if it were something like:
`https://ibos.netlify.app/productlist?page=2`?

**Comment by piotrwicijowski** [comment]
The approach you presented with `https://ibos.netlify.app/?page=3` looks fine - that's because we are still, in fact, on the main page, so no need to have a sub-page of `productlist`.
And when it comes to nesting of `ProductList` in `WelcomeScreen` and it's impact on getting access to the `page` url parameter - did you try to do it, or not yet? Have you encountered any problems, or are we just hypothesizing about "possible complications"?

**Comment by fromITzerotoIThero** [comment]
👍 
Yes and no - I'm in the process and have code that doesn't work as expected (no changes in component hierarchy made) - and that's when I realized I don't quite understand the whole process (as in my first comment). 

I'll push the changes I've made so far and do some more trial and error :)

**Comment by piotrwicijowski** [comment]
Once you push the changes I'll try to have a look.

**Comment by fromITzerotoIThero** [comment]
No rush, I have some ideas to explore, that might work ;)

**Comment by fromITzerotoIThero** [comment]
Oh, seems I've fixed it, I needed a different react-router hook :)

**Comment by fromITzerotoIThero** [comment]
At that point - can I leave `ProductList` state management locally, or should I use Redux for it?

**Comment by piotrwicijowski** [comment]
Keep it locally for now

**Comment by fromITzerotoIThero** [comment]
W., 

So the user story seems complete to me - simple pagination works as expected.

I have 2 questions though:

1. I was thinking about `count` - it's a number that (at least for now) doesn't change. 
- should I fetch it every time I make a request to supabase?
- or is it wiser to fetch it only once, after the component mounts?
- I'm trying to grasp what's wiser, maybe more efficient, but I can't tell - maybe it's better to keep it altogether in one request?
- is it even worth bothering in my case?
- I left the version with separate useEffects for fetching `count` commented-out

2. Another one concerns the original version of useEffect:
- when it comes down to calculating `.range()` - should it be based on `currentPage` value or rather `page`?

**Comment by piotrwicijowski** [comment]
Sorry it took me so long to answer, but here we are:
1. Let's fetch it every time just in case - you never know if the backend does not get some new items in the meantime. It is less efficient, but makes sure that in case the number of the items changed in the meantime, the user will have the full view without needing to do a full refresh
2. Looks good to me - it depends directly on page, which is taken from the query string, and I think that's a better approach, because this way we can be more sure that the url and the state on the page will be in sync
