### ISSUE TITLE
Image Carousel Component

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#16]
As a user, whenever I open a product page, I want the images to be browsable by using a carousel

Technical implementation details:
- Create ImageCarouselComponent
- It should take a list of images as props
- Display "current image" indicator  - the filled and empty dots ○○○●○ - make it into a separate component
  - Clicking on the dots on the indicator should navigate to image on the specified position
- Display left/right arrows on the sides of the image, clicking on them navigate forward/backward

Edge cases:
- If the carousel would contain only one image, do not display the indicator dots and the arrows
- If the carousel is displaying the first image, do not display the left arrow
- If the carousel is displaying the last image, do not display the right arrow

Designs url: 
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=aa6c056f-666a-8012-8001-dfd5bc1f9f51&section=interactions&index=2

**Comment by fromITzerotoIThero** [comment]
Dear W., 

so I wanted to create the ImageCarousel but I'm not sure what's the best way of doing it in terms of branches - would the following be a proper way of going about it:

1. Create new `feature/16-image-carousel branch and then:
2. Create another branch for `feature/16-image-carousel-indicator branch stemming off of the previous one? :)

**Comment by piotrwicijowski** [comment]
Deer G.
I suggest you do everything related to one task/one PR in single branch. If a change would warrant splitting up the work into several branches, it would also warrant splitting up the tasks. Having just `feature/16-image-carousel` should suffice

**Comment by fromITzerotoIThero** [comment]
And that's what I'm gonna stick to! Thx!

**Comment by fromITzerotoIThero** [comment]
Woops!

I'm not sure how to code the "clean" version of `ImageCarousel`, got a little lost! 
I have some impaired version on the master... 
What's the best-standard way of dealing with it?

1. Checking out for master and deleting the `ImageCarousel` altogether;
2. Then creating new one on `feature/16-image-carousel?

**Comment by fromITzerotoIThero** [comment]
W., 

I'm about to start making an interactive ImageIndicator component. I'll be working on the dedicated branch for ImageCarousel and once I write sensible code for it, I'll commit & push it for that branch. 
However, will that be reflected in the draft PR I just made?

**Comment by piotrwicijowski** [comment]
If the branch that you will be pushing to is the branch in PR, and that's `feature/16-image-carousel` then yes, it will be reflected in the draft PR.
