### ISSUE TITLE
Product Page - initial version

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#17]
As a user, when I click on the Product List Item on the main page, I want to be navigated to the Product Page

Technical implementation details:
- Create Product Page component
- Clicking on the Product List Item should navigate to the Product Page (use the `id` of the product in router navigation
- Use the Carousel Component to display the images

Design url:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=aa6c056f-666a-8012-8001-dfd5bc1f9f51&section=interactions&index=2

**Comment by fromITzerotoIThero** [comment]
W., 
I've added routing to `ProductPages` by wrapping each element in `Navlink` and here I have a question - is that the right way to do it? It works just fine, but Inspector got me thinking - `Navlink` is translated into an `<a>` element which by default is inline and yet it's wrapping block `div`s...?

**Comment by piotrwicijowski** [comment]
Wrapping block elements with inline, and vice versa is completely valid, as long as it works.

About the `ProductPage` - just make one, no need to have two, that would be very confusing

**Comment by fromITzerotoIThero** [comment]
Thx! :)

**Comment by fromITzerotoIThero** [comment]
Oh, and another question - the IBOS I fire on my computer is based on the code I have locally on my computer. How do you get the hang of what the viewer gets to see if it's just the code in a repository and not the app on the production server?

**Comment by piotrwicijowski** [comment]
If you send them a link to your repo, then they will be able to see all of the branches - at least those that you have pushed to github. That's the list that they will see:

![Image](https://user-images.githubusercontent.com/18663652/229850341-3fbbdd93-a43c-4ff8-a8a6-ddfa4f24068f.png)

However, I don't think that they will bother with looking at anything other than the master branch - the convention is that if it is in master, it means that it is "working", and branches can be in some state that may or may not even compile. But in general, yes, the idea is to eventually merge your changes back into the master branch (or even better, make a PR, and once it is approved - merge the branch through the PR)

Regarding your second question on "how to see what others would see" then there are many ways. One of them would be to keep a "clean" copy of the code on the side on your machine, fetch there from git and run it - it will let you see if a clean state really works. Or, alternatively, you can utilize something like stackblitz, which allows you to run any frontend application inside the browser. For IBOS the link would be https://stackblitz.com/github/fromITzerotoIThero/IBOS/ . I made a small adjustment so that it would play well there (so make sure to pull the latest master branch from github). What's nice about it is that you can share this link with anyone and they will be able to see your application - no need to install npm, no need to compile, no need for VS Code - just open the link in a browser. And, if we want to get fancy at some point, we may even deploy your application to a production environment one day.

Hope that helps.
