### ISSUE TITLE
Reusable BasicCard component

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#3]
Based on the `WelcomeScreen`, extract a `BasicCard` component:
- Make it have the following properties:
  - Title
  - Description
  - Button text
  - Button link
- Modify the `WelcomeScreen` to use this component

**Comment by fromITzerotoIThero** [comment]
W., by Button text and Button link you mean one button with text on it (like in the designs), but that links us to subpages?

**Comment by piotrwicijowski** [comment]
Yes, I mean that there will just be one button, but that button needs to have two separate properties - button text is what will be displayed, and button link is "where the button leads to"

**Comment by fromITzerotoIThero** [comment]
W., so I'm trying to figure out, from like a high level, how to create this BasicCard component and I'm not sure I'm getting it all right, but this is how I understand it: 

1. I'm supposed to create some sort of template, which is going to fetch data (text, the welcome text and domains overview and different color-styles) from elsewhere (where?)?

2. And then it's only enough for me to have all that info stored somewhere and React is going to do some magic trick to glue it all together?

**Comment by piotrwicijowski** [comment]
1. In this task we are not fetching data from anywhere, the welcome screen can have this data hard coded in the source code.
2. The name of "magic trick" in react is called "props", so if you are looking at tutorials or documentation, then that's the name you should look for

**Comment by fromITzerotoIThero** [comment]
Oh yes, I've already seen it and it felt like it's super useful and to be used in the near future :)

But as for the BasicCard component - the idea with an empty template with styling applied - is that right?

**Comment by fromITzerotoIThero** [comment]
W., I've created this BasicCard component, leaving a lot to be desired, but I'll leave it for now, since I see I need to dive into JS and these props thing to move on...

**Comment by fromITzerotoIThero** [comment]
W.... these props are insane! :O! I'm gonna play around a bit with them before I commit the BasicCard component, but I have one question about the Welcome Screen - the way I see it now, is that I actually do not need this component any more and I could simply pass different props from <BasicCard /> in App.js, but maybe I'm missing something?

**Comment by piotrwicijowski** [comment]
What's so insane about them? They just look like passing parameters to a function ;)
Keep the Welcome Screen component, soon enough (in the routing task) you will need it.

**Comment by fromITzerotoIThero** [comment]
For a person with nearly no experience of passing parameters to a function it feels great to use them! XD
Ayay, I will!

**Comment by fromITzerotoIThero** [comment]
W., for naming props I should go with camelcase, right?

**Comment by fromITzerotoIThero** [comment]
And one more one ;) That makes sense, right? 

` <a href={buttonLink} className={styles.button}>{buttonText}</a>`

**Comment by fromITzerotoIThero** [comment]
They do, thx! 

I've created the BasicCard component and changed the WelcomeScreen along the same lines. 

Could you W.:

1. give me a hint for positioning the button, like in which direction should I go?
2. tell me if I can move on to the routing task or should I explore this some more?

**Comment by piotrwicijowski** [comment]
Make it so that the Welcome Screen is just a container that holds the BasicCard (because right now I see it is basically a copy of BasicCard)
1. For button positioning, try wrapping it in a `<div>`, and using a flexbox in that `<div>`, so that the button would be positioned on the right (hint - you can use `margin:auto` if you need to align a single element in flexbox). What is more, do not force the height of the component to be 400px;
2. You can explore this a bit more, but without going too crazy.

**Comment by fromITzerotoIThero** [comment]
Oh thank you! :) That was helpful! 

1. Eventually I didn't go with `margin: auto` but it seems the styling works fine now. 
2. I changed the WelcomeScreen the way you said. For now I left the WelcomeScreen.module.css the way it is though it seems redundant. 
3. So now I'll plunge myself into Routing :)
