### ISSUE TITLE
Add routing

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#4]
Add routing to the application:
- Install [react-router](https://www.npmjs.com/package/react-router) package
- Create dummy page for verifying that navigation works
- Replace the contents of `App` component to contain the routing definitions
- Add top level route that will display the `WelcomePage`
- Add a dummy route that displays the dummy component
- Modify the `Header` component to use actual links that open each page
- Modify the `BasicCard` component's ButtonLink property to use an actual link
  - In the `WelcomePage` modify the usage of the `BasicCard` so that the ButtonLink points e.g. to the dummy page

**Comment by fromITzerotoIThero** [comment]
W., on installing the react-router package I've learnt there are 2 versions of react-router one for React DOM (which I seem to have) and the other for React Native. 

Based on the info here:
https://www.npmjs.com/package/react-router 
I assume everything will be running just fine, all I need to do is use: 

_import blablabla from 'react-router-dom' rather than 'react-router'?_

**Comment by piotrwicijowski** [comment]
Make sure to use the react-dom variant, because "React Native" is a completely different framework for creating mobile applications.

When it comes to doing the import, then some parts will require you to import the *-dom package (e.g. `createBrowserRouter` is DOM specific), while others will use the `react-router` generic package. Just follow the tutorials. And make sure to avoid any "React Native" tutorials

**Comment by fromITzerotoIThero** [comment]
Ok!

**Comment by fromITzerotoIThero** [comment]
Oh W., I haven't done #4 yet, but I have a feeling (looking at this todo list) that if I replace the contents of App() in App.js with Routes it's gonna screw up the looks of the app as we have those high-level divs with styles applied to them. 

Am I wrong?

**Comment by fromITzerotoIThero** [comment]
Ah, never mind, those in-advance questions are stupid. 
I'll play around with it :)

**Comment by piotrwicijowski** [comment]
As you already correctly assume, then yes, styles will be messed up a bit, but after that everything will be a bit more organized. You are correct with putting the routes into the App.js, and hopefully you can now understand why I insisted on keeping the WelcomeScreen component - since it will now be routed to (you may need to move the hard-coded strings from App.js into the WelcomeScreen, but that's ok)

**Comment by fromITzerotoIThero** [comment]
Oh W., I'm struggling with this ButtonLink property in the BasicCard component and I can't figure out why this doesn't work the way I did it :((( 

I've tried to do it with the <Link> component, along the same lines as in the Header and passing props inside of `to=` attribute, but well that didn't do the job, any hint?

**Comment by piotrwicijowski** [comment]
It's the `z-index: -1` that's making a mess here - it gets "below" its parent div, and it does not receive the clicks

**Comment by fromITzerotoIThero** [comment]
Oh I knew it's gonna run me into trouble! Thx! :D
