### ISSUE TITLE
DomainsOverview page with list of domains

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#5]
Create `DomainsOverview` page:
- Make sure the routing, header, and `WelcomePage` card components link to that page
- Fetch data from supabase backend
- Display a list of `BasicCard` components, each for the domain that came from the backend, fill in the props (for now we don't have a page for domain details, so we can leave it blank)

Designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=0287358f-ba0f-80b3-8001-af163e079ce4&section=interactions&index=1

**Comment by fromITzerotoIThero** [comment]
Hey W.!

Since I know pretty much nothing about fetching backend data (I did look at a couple of short tutorials in the field, but not with much success), I'm wondering how deep do I need to get into it to complete the task XP 

I might be completely wrong, but what I see I may need to learn and understand is the hooks `useState` and `useEffect`, all those things you did in the DomainList component. 

But, off the top of my head, since the DomainList is already fetching the names of the domains I need, I thought I could use it somehow as props and pass it to my DomainsOverview component. Does that make any sense?

**Comment by piotrwicijowski** [comment]
Hi G.

Yup, the intention of this task is for you to learn, that often in programming we already have a working solution for some sort of a problem, and we just need to do a similar but related thing in another place. So basing the code on the DomainList is the right way to go.

On one hand, you can just blindly copy, paste and modify those code parts for data fetching, but on the other you are correct to assume that a bit deeper understanding of `useState` and `useEffect` will help you in the long run.

And finally, the currently existing cod for data fetching only shows the title of the domain, but we also need a description, so this will be an exercise for you to figure out "how do I check what other useful data do I get from the backend"

Regarding pages - yes, that's 100% correct. If a jsx component is containing a full page, and will most likely not be reused, it can be moved to `src/pages` directory.

**Comment by fromITzerotoIThero** [comment]
So I see the idea with passing domains names as props from `<DomainList />` component is not the way to go.

Thx! I'll learn how to use those hooks!

If you could give one more advice - (since I'm learning the very basics of JS right now), in the percent of time spent, how much should I spend it on pure JS and how much on React?

**Comment by piotrwicijowski** [comment]
About the percent of time spent on React vs JS - it's a very hard question. I guess you'll learn enough JS through doing React related tasks, since React is using JS directly. Along the way you'll come across different new concepts that you may have not know, so then would be a good time to learn them. So if you come across `useState` then it's time to learn that thing in React. Next up you may come across things like `arr.map(x => doSomethingWith(x))` - and that's a JS concept. My advice is that try to spend enough time on each concept so that you can understand and explain it at a basic level, and that you are able to use that concept you have learned in another place.

Also, it's hard for me to tell you how much this or that you need to learn, since I don't know how much you already know. So "learn as you go" would be the best advice that I can give.

**Comment by fromITzerotoIThero** [comment]
Thx, that's helpful! `

**Comment by fromITzerotoIThero** [comment]
W., how to Polish devs call constant variables in Polish? "Zmienne" or "stałe" or maybe "stałe zmienne"?

**Comment by piotrwicijowski** [comment]
If they are constants, that means that they are not variable ;) And Polish devs just call them "consts"

**Comment by fromITzerotoIThero** [comment]
I know it sounds illogical, but that's how they call them on MDN XD So I can expect my future colleagues to be like "Garza, stworzyłem consta num1?" XP

**Comment by piotrwicijowski** [comment]
I'll not argue with MDN then ;) And yes, Polish devs tend to mix a lot of English and Polish when talking about dev stuff.

**Comment by fromITzerotoIThero** [comment]
Thank you W., I know it's not the most important thing to know right now, but it was bugging the hell out of me, now I can start a New Year with a peaceful mind XD

**Comment by fromITzerotoIThero** [comment]
W., 

so it seems it's complete, but on changing the text color from rebeccapurple to black I have this question emerging about styles - in the `DomainsOverview` component, on the bottom, there's this `<li className={styles.element}>`  wrapping our `BasicCard `compo and I can tell that it overrides the styles of `BasicCard`, which sounds logical to me.

But what if I want style just one element from the `BasicCard`, say a title, and give it a color of rebeccapurple, how to target it?

**Comment by fromITzerotoIThero** [comment]
I see there's the task #10 dealing with colors, should I leave it up till then?

**Comment by fromITzerotoIThero** [comment]
And I have a few minor workflow questions: 

- where should I write questions that are not directly related to a given task? Do you think creating a separate task like Miscellaneous Questions would to the job? 

- if I edit a comment I've made, do you get a notification about it? It looks very handy to me, but as long as you're not troubled with notifications :)

- once I mark a task as 'done', can you add comments there?

**Comment by fromITzerotoIThero** [comment]
And I know what the "M" word was! "MOUNTING" (componentDidMount, componentDidUnmount...) :) 

Should I dive into it now, or should I leave it? Correct me if I'm wrong but after watching tutorials on useState and useEffect I got an impression since functional compos are superseding the class ones this 'mounting' thing is not very important now?

**Comment by piotrwicijowski** [comment]
1. We don't want any element to have rebeccapurple text at the moment, at least in the designs I can't see anything like that. Unless that was a hypothetical question on "how would I make this happen if I needed to" then yes, #10 is the place where we will focus on customizing the styles
2. You say "it seems complete" - can you please push it to the repo?
3. For communication purposes I would caution against creating a tasks that are not tasks, maybe just send an e-mail.
4. I don't know if the notifications are sent on comment edits, but the question is - why do you want to make an edit? If it is for some minor tweak that does not change the whole idea (fixing a typo, better formatting) then it is ok, otherwise I'd say - just make another comment.
5. You can add comments to tasks that are closed, no problem
6. We don't worry about mounting (and other lifecycle methods that are for `class`-type components). And yes, functional components (I have never head it being shortened to "compos") are superseding the class ones.

**Comment by fromITzerotoIThero** [comment]
Thx!!! :)

**Comment by piotrwicijowski** [comment]
There is still a huuuuge margin between the cards, I hope you can fix that quickly

**Comment by fromITzerotoIThero** [comment]
Whoops! 
Done.

**Comment by fromITzerotoIThero** [comment]
W., 
just now I’ve noticed that elements on the DomainsOverview page are displayed with extra horizontal margins and I reckon it has something to do with the fact that they are wrapped in <li> elements. I’d like to fix this but in a time-effective manner, could you give me any hint?

**Comment by piotrwicijowski** [comment]
Do they need to be wrapped in the list elements? The original `DomainList` had those ul and li just to have some html, but your `DomainOverview` does not need it anymore

**Comment by fromITzerotoIThero** [comment]
Oh, you're right, who said they had to be? So i eventually wrapped it in a `div`, I was wondering why IBOS fails to compile if instead of `div` I use this empty element `<>`?

**Comment by piotrwicijowski** [comment]
The empty element `<>` has special meaning and is supposed to be used only for wrapping whole components. Besides, do you need to wrap the `BasicCard` elements with anything?

**Comment by fromITzerotoIThero** [comment]
Ok!
As for the `BasicCard` elements within the `DomainsOverview` component I don't know how else to do it without the browser throwing errors... 

` return (
      <div>
        {domains.map(domain =>
            <BasicCard title={domain.name} description={domain.short_description} buttonText="Learn more" />
        )}
      </div>
    );
`
