### ISSUE TITLE
Create Accordion and AccordionElement component

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#6]
Create `AccordionElement` component:
- Has an `expanded` state
- When not expanded, it shows only the `title`
- Contains a chevron-up or chevron-down icon on the right side depending on the collapsed state (icons based on task #9)
- When collapsed, the whole row can be clicked, and clicking expands the `AccordionElement`
- When expanded, clicking on the chevron icon collapses the `AccordionElement`
- Show a color accent bar on the side, but only if expanded
Create `Accordion` component:
- Contains a list of `AccordionElement` components
- *bonus requirement* - make sure that only one `AccordionElement` can be expanded - so if e.g. first element is expanded, and the user clicks on second element, the first will then be collapsed

Designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=0287358f-ba0f-80b3-8001-af163e079ce4&section=interactions&index=3

**Comment by fromITzerotoIThero** [comment]
W., 
when it comes down to the `Accordion` component, the way I see it can be done is with the use of useState and useEffect, with fetching data for the top description (I mean, making use of the `details` from our database) and creating a list of empty `AccordionElements`  (because for now we don't have that data stored anywhere)?

**Comment by piotrwicijowski** [comment]
Let's discuss that tomorrow in more detail. But in short, we don't want the `Accordion` to fetch any data - we want it just to be a consumer of data that is provided from its parent, same would be for `AccordionElement`. That's because we want this component to be generic and usable in different scenarios.

**Comment by fromITzerotoIThero** [comment]
Alright... so sounds like props should come into play? We'll discuss that in the evening and I'll try to create a skeleton for both the components with what I already know :)

**Comment by fromITzerotoIThero** [comment]
Hey W., 
I have a question - from a senior dev's perspective, how frequently the alternative box model is used? I'm not using it, but since I'm starting to see it across different tutorials, maybe it's something I should introduce?

**Comment by piotrwicijowski** [comment]
Hi G.
You are actually using it - the index.css has a rule that sets `box-sizing: border-box` on all elements. The truth is that the "alternative" box model is used 99.999999% of the cases in real world because it is the most logical and reasonable option, and only due to compatibility and historical reasons the default is `content-box`.
In general, don't worry about it. In IBOS it is set globally and you don't have to do anything else to use it.

**Comment by fromITzerotoIThero** [comment]
Oh good then :) I agree it's so much more logical! Thx!

**Comment by fromITzerotoIThero** [comment]
So it seems I've managed to create an AccordionElement component that does collapse, but there's one thing that's driving me crazy - the layout of the title... could you please take a peek at my code? 
I don't understands why it doesn't work the way it should... with `justify-content: space-between;` shouldn't the text and the icon lay at the opposite ends of the flex-box? :/

**Comment by fromITzerotoIThero** [comment]
Oh I have another question, the `AccordionElement` I've made is simple, what changes is pretty much the display of content and the icon type, but there are more things to do - the bar, the 'disabled' state of the title (except for chevron up) when expanded and I'm trying to figure out how to do it...

I'm not too comfortable with creating functions yet so I thought I might (this may be worded in a weird/pre-junior way XP) try to maybe add a CSS class to this "expanded" state to do all that styling stuff? Does that make any sense?

**Comment by piotrwicijowski** [comment]
About the centering issue: the `space-between` on the title level is ok, it's just that the title itself does not take the whole width of the `.accoridion__element`, which is the parent. For that you need to set `align-items: stretch;` on that parent. Tomorrow we can talk about how to diagnose such behaviors.

About "how to do it" - of course some of the behaviors that are in the task will require that you add an "expanded" class and use that for conditional styling. That would be e.g. the margin between an expanded element and other elements. But for some behaviors (like the fact that the whole title will not be clickable, just the chevron) then you can use the conditional behavior in jsx, like you already do with the `{expanded ? <TheStructureWhenExpanded> : <DifferentStructureWhenCollapsed>}`. So you are generally on the right track :)

**Comment by fromITzerotoIThero** [comment]
Thx for the tips! :)

**Comment by fromITzerotoIThero** [comment]
W., so I've managed to: 

1. **apply some conditional CSS classes** - though actually not the way I wanted (now it's like "either or", not "and"), but it's something to work on;

2.  **apply some margins** - and again far from perfect (I don't know yet how to manage the top margin of the first `AccordionElement,`);

3.  _bonus requirement_ - not done, I guess it has to do with the `Accordion` component (same for the margin of the first `AccordionElement`) but my head is about to explode now and I have to do sth simple now XD 

So till the evening! :)

**Comment by fromITzerotoIThero** [comment]
W., I thought I would be able finish it off in an instant but erm... some problems emerged :P I need your advice!

1. The `Header` and the grey bar on the active navbar entry - hmm... I can't figure out why it's the width of the parent container, I can't remember what you did (without wrapping things in divs or these kind of tricks) that made it work the way we wanted.

2. The margins of the `AccordionElement` - so I know how to make the first item not have the top margin, but something I didn't expect happens when 2 adjacent items are open - there is no margin collapsing and I'm trying to find out how complicated it may be to fix this.

**Comment by piotrwicijowski** [comment]
1. First advice for the future - when working on one functionality, just stick to that and don't jump around, e.g. to the header. So for now please revert all changes related to the header, since there is a separate task for that. But just fyi, you need to make the `.navbar__entry{ position:relative }`, so that the `absolute` would work against that element.
 
2. In order to get the margins to collapse, the parent element should not be `display: flex`. I think you can safely remove that on the `.accordion` level, because it already is `direction: column`, so it visually would not differ from the default display.

**Comment by fromITzerotoIThero** [comment]
Oh, unnecessary mess, that was foolish!  
 
Da! `position: relative` and everything's fine! So the Header is fixed.

I've also changed those "inset-shadow-bars" to ::befores & ::afters and fixed the margins they way you suggested, I just need to introduce the classnames npm to reduce the code before I finish off this task :)

Thx!

**Comment by fromITzerotoIThero** [comment]
OK, so I've added the classNames npm to the `AccordionElement`.) I've also used it for the collapsible content (for now I understand it better than the previous version, which I left commented out for now). 

By mistake I also did some weird thing with pushing a commit, than did some pulling and merging, but hopefully the code is fine by now XP

**Comment by fromITzerotoIThero** [comment]
Oh and I forgot to tell how much I like the user stories you've added! My oh my, IBOS starts turning into a shop! :O!

**Comment by fromITzerotoIThero** [comment]
I've noticed a little bug though in my `AccordionElement` - according to the designs, the horizontal bar on the collapsed `AccordionElement` should disappear once the item below it expands, whereas with my code it stays in place. 

I thought I could handle it with mixing CSS selectors but I've been doing it for quite a while now with no effect. Is this the right way to go?

**Comment by piotrwicijowski** [comment]
Regarding the horizontal line - I can show you today. And I admit, it's a bit trickier than I initially thought ;)
