### ISSUE TITLE
DomainDetail page with long description and list of themes

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#8]
Create a `DomainDetail` page:
- Can be routed to using the domain's id
- Fetches the data for the domain (based on the task #6)
- Contains a `DomainHeader` component:
  - Has a title and back arrow button (icon based on #9)
  - Back arrow navigates to `DomainList` page
- Has an accordion component with all themes listed themes (based on the task #7)
- Update the links in navigation and domain cards to open the details page for all domains

Designs:
https://design.penpot.app/#/view/0287358f-ba0f-80b3-8001-af163e079ce3?page-id=0287358f-ba0f-80b3-8001-af163e079ce4&section=interactions&index=2

**Comment by fromITzerotoIThero** [comment]
W., when it comes down to the `DomainDetails` page, the way I understand it:

- it should be a cluster of other components and data fetching

- with styles coming only from the outside, like there should be no need to add extra styles in `DomainDetails.module.css` or even more so, such css file should not even exist?

**Comment by piotrwicijowski** [comment]
It will be a cluster of other components, and those components will hold their own styles. But there still may be some need for creating a css file, e.g. for general layout of those components. So it can exist, I don't see a problem with that

**Comment by fromITzerotoIThero** [comment]
W., you need to help me out!

I have some big hole in my JS understanding and I do not fully understand all the code behind data fetching, states and objects, but I really want to finish my this week's task.

So I started creating the `DomainHeader` component, fetched the data, but I don't know how to tell it to render just the one related to the specific domain, I didn't manage to come up with any sensible analogy of what we did last week that would work. Or maybe this selection should be done at the level of the `DomainDetails` page. I really don't know. 
What should I do?

**Comment by piotrwicijowski** [comment]
The way I see it, the `DomainHeader` should not be fetching the data, but should just get the data from the outside (via props). And the `DomainDetails`, since it already has the data fetched, should only include the `DomainHeader` component and pass the required pieces of data to it. I hope it makes sense.

**Comment by fromITzerotoIThero** [comment]
Ok, do the `DomainDetails` page is starting to take shape, I just need to make the right details page render for the right domain. I suppose it has something to do with routing using the domain's id, I'll try to figure it out :)

**Comment by piotrwicijowski** [comment]
That's correct, you need to investigate routing and get a hold of domain's id. Fingers crossed

**Comment by fromITzerotoIThero** [comment]
I've managed to create a link for each `DomainDetails` page including the domain.id, but I can't get it to render the right content, any hint on what I am doing wrong? :)

**Comment by piotrwicijowski** [comment]
You were on the right track with `useParams`. However, you imported it from the wrong place. I'd suggest you rely on the autocomplete to automatically create those imports for you. The line that you were missing was 
```
import { useParams } from 'react-router-dom';
```
For some reason you imported it from 'react`. Then you can safely uncomment the `useParams` line, and use that `id` parameter in the `.eq` filtering

**Comment by fromITzerotoIThero** [comment]
`face palm emoji should go here`!
It works! XD XD XD <3
