### ISSUE TITLE
Include and use material icons

### ISSUE THREAD

**Issue by piotrwicijowski** [fromITzerotoIThero/IBOS#9]
Include material icons in the project
Learn how to use those icons in your own components

**Comment by fromITzerotoIThero** [comment]
Oh W., I just wanted to share with you my awe/admiration for Material Icons, man, open resources now seem to be all you need right now! And these Material Symbols, man, it's jaw-dropping!!!

**Comment by fromITzerotoIThero** [comment]
Anyways. do you want me to do it using material-ui/icons or react-icons package? 
It sounded reasonable to me to import only the icons I want, so I like the idea with react-icons, but I might be missing sth here?

**Comment by piotrwicijowski** [comment]
Hmm, react-icons sounds interesting, since it contains a lot of other icon packs. On the other hand, it does not contain all of the icons and icon variations of the material icons set.
And when it comes to "importing only the icons you want" then it is also possible with material icons, if you click on any sample here https://mui.com/material-ui/material-icons/ you can see that it gives you import option just for that icon.

**Comment by piotrwicijowski** [comment]
I have added one icon usage to the designs, let's see if you can spot it

**Comment by fromITzerotoIThero** [comment]
Oh you've added a homepage symbol :)

**Comment by fromITzerotoIThero** [comment]
One more piece of advice needed :) How should I add/style Material Icons components in my navbar so they don’t break my navbar’s layout? I’m looking for some general tips for further digging like: “wrap it in sth and add styles to that wrapper”/ “add styles directly to the Icon component”/“add it as a ::before pseudoelement”?

**Comment by piotrwicijowski** [comment]
If the problem is with "breaking layout" then I'd recommend wrapping it in a `<div>` or something. But this advice may not work 100% of the time, so sometimes other approaches may be valid too. Feel free to experiment, and when we will reach the stage where we'll be doing code reviews, then I'll do my best to spot any weird results of such "experiments".

**Comment by fromITzerotoIThero** [comment]
So I've managed to fine-tune the `Header` a bit, it looks nearly fine except for the thickness of the icon, I can set `color` and `size` property on it with CSS, but I can't figure out how to set `weight`... 

I thought it's supposed to behave like a regular font, but `font-weight` doesn't work, I've seen people recommend turning the icon to an SVG element and playing with `stroke` property, but isn't it doable in a simpler way? 

BTW, can I mark the task as done even though I'm clearly not a whizz at styling mui icons?

**Comment by piotrwicijowski** [comment]
When it comes to the stroke width, then there is nothing you can currently do about it. We can close the task.
Also, make sure that if there were any css rules that you added as an experiment, but don't work in the end (like the `weight: lighter`) then remove it from the final version.

**Comment by fromITzerotoIThero** [comment]
Thanks for the help! :) Removed!
